### ISSUE TITLE
Check for empty $kalmediaassign

### ISSUE THREAD

**Issue by mwehr** [YU-MITC/moodle-mod_kalmediaassign#1]
Hi,

I think there is small bug in lib.php - Line 194
https://github.com/YU-MITC/moodle-mod_kalmediaassign/blob/6bb83fde3c744e0908f23e686583c58715ade6be/lib.php#L192-L198
The check for empty $kalmediaassign should be negated.

regards
Mario

**Comment by YU-MITC** [comment]
Hello @mwehr,

Thank you for your report.
We fixed lib.php in mod_kalmediaassign.

Regards,
